---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: 'Get Copr repositories'
      command: "copr-cli list"
      register: copr_repos

    - set_fact:
        scratch_repos: "{{ copr_repos.stdout.split('\n') | select('match', '^Name:') | list | replace('Name: ', '') }}"

    - set_fact:
        scratch_repos: "{{ scratch_repos | select('match', '.+scratch.+') | list }}"

    - name: 'Remove scratch repositories from Copr'
      command: "copr-cli delete @theforeman/{{ item }}"
      with_items: "{{ scratch_repos }}"
