- hosts: localhost
  gather_facts: no
  vars_files:
    - .tmp/copr_repo
  tasks:
    - name: 'Run repoclosure'
      command: "repoclosure -c repoclosure/el7.conf -t -r scratch --repofrompath=scratch,https://copr-be.cloud.fedoraproject.org/results/{{ copr_repo }}/epel-7-x86_64/ -l el7-base -l el7-scl -l tfm-ror51-copr"
      register: output

    - name: 'Cleanup'
      file:
        state: absent
        path: scratch/

    - debug:
        msg: "{{ output.stdout_lines | join('\n') }}"
