---
- hosts: packages
  any_errors_fatal: false # don't bomb out the entire playbook if one host (i.e. package) fails
  gather_facts: no
  serial: 1
  roles:
    - git-annex-setup
    - ensure-package

- hosts: all
  gather_facts: no
  tasks:
    - name: 'Create .tmp build directory'
      file:
        state: directory
        path: .tmp
      run_once: true
      tags:
        - always

    - set_fact:
        copr_repo: "@theforeman/tfm-ror51-scratch-{{ 999999999 | random | to_uuid }}"
      run_once: true
      tags:
        - always

    - name: 'Write copr repo name to vars file'
      copy:
        content: "{{ 'copr_repo: ' + copr_repo | to_yaml }}"
        dest: ".tmp/copr_repo"
      run_once: true

    - include_tasks: tasks/create_copr_repo.yml
      with_items: "{{ chroots }}"
      run_once: true
      tags:
        - always

- hosts: packages
  any_errors_fatal: false # don't bomb out the entire playbook if one host (i.e. package) fails
  gather_facts: no
  tasks:
    - include: tasks/setup_sources.yml
      tags:
        - always

    - name: 'Build SRPM'
      command: 'tito build --srpm --output=../../.tmp --scl=tfm-ror51'
      args:
        chdir: "packages/{{ inventory_hostname }}"
      register: srpm_build
      tags:
        - always

    - name: 'Run build'
      command: "copr-cli build {{ copr_repo }} {{ srpm_build.stdout.split('Wrote: ')[1] }}"
      register: build_status
      tags:
        - always

    - debug:
        msg: "{{ build_status.stdout_lines | join('\n') }}"
