---
- set_fact:
    build_tasks: "{{ target_release.stdout_lines \
      | select('match', '^Created builds:.*') \
      | map('regex_replace', '^Created builds:\\s(\\d+)', '\\1') \
      | list }}"

- name: 'Watch task(s)'
  command: "copr-cli watch-build {{ build_tasks | join(' ') }}"
  ignore_errors: yes
  register: build_status
  when: target_release | succeeded

- name: 'Failed build'
  fail:
    msg: 'The build in build has failed'
  when: build_status | failed
